default: &default
  adapter: postgresql
  encoding: unicode
  pool: 4

development:
  <<: *default
  url: postgres://localhost/uirelator_dev

test:
  <<: *default
  url: postgres://localhost/uirelator_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
